version: '3'
services:
    php:
        image: jtn7/faqbot:php-pwd
        container_name: php_project
        volumes:
            - ./:/code

    nginx:
        image: jtn7/faqbot:nginx-pwd
        container_name: nginx_project
        links:
            - database
        volumes:
            - ./:/code
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 80:80

    database:
        image: postgres:10-alpine
        container_name: postgres_project
        environment:
            POSTGRES_DB: dbname
            POSTGRES_USER: example
            POSTGRES_PASSWORD: example
    
    cache:
        image: redis:3-alpine
        container_name: redis_project

    elastic:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
        container_name: elastic_project
        environment:
            discovery.type: single-node